spring.application.name=recruitment-platform-api
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

###
app.jwt.base64-secret=${JWT_BASE64_SECRET}

###
app.jwt.access-token-validity-in-seconds=900
app.jwt.refresh-token-validity-in-seconds=604800
###
spring.config.import=optional:file:./application-local.properties
